services:
  s-ui:
    image: alireza7/s-ui:latest
    container_name: s-ui
    volumes:
      - ./db:/app/db
      - ./cert:/app/cert
    tty: true
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      - caddy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-size: 10m
        max-file: "5"
